src/sk/ibm/sa/dao/FriendsController.java
package sk.ibm.sa.dao;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import sk.ibm.sa.Friends;
import sk.ibm.sa.User;

public class FriendsController {
	
private DbFriendDao friendDao;
private UserController userController = new UserController();
	
	public FriendsController() {
		friendDao = DaoFactory.getInstance().dbFriendListDao();
	}

	public void addFriends(Friends friends){
		friendDao.addFriends(friends);
	}
	
	public List<Integer> getFriendsIdList(int id){
		
		List<Friends> friends = friendDao.getFriendList(id);
		List<Integer> friendsID = new ArrayList<Integer>();
		
		for(Friends friend : friends){
			if(friend.getUser_id1() == id) friendsID.add(friend.getUser_id2());
			else friendsID.add(friend.getUser_id1());
		}
		
		return friendsID;
	}
	
	public List<User> getFriendsList(int id){
		List<User> friends = new ArrayList<User>();
		List<Integer> friendsID = getFriendsIdList(id);
		
		for(int i : friendsID){
			friends.add(userController.getUserById(i));
		}
		
		return friends;
	}
	
	public List<User> getNoFriendsList(int id){
		List<User> allUser = userController.getAllUsers();
		List<Integer> friendsID = getFriendsIdList(id);
		friendsID.add(id);
		
		
		for (Iterator<User> it = allUser.iterator(); it.hasNext(); ) {
			if(allUser.size() == 0)return allUser;
			
		    User user = it.next(); 
		    for(int i : friendsID){
		    	if(i == user.getId_user())
		    	 it.remove();    	
		    }
		}
		
		return allUser;
	}
	
	
}












src/sk/ibm/sa/dao/UserController.java
package sk.ibm.sa.dao;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import sk.ibm.sa.Country;
import sk.ibm.sa.User;
import sk.ibm.sa.utils.LoginUtils;

public class UserController {
	
	private UserDao userDao;
	
	public UserController() {
		userDao = DaoFactory.getInstance().getUserDao();
	}

	public void addUser(User user) {
		userDao.addUser(user);	
	}

	/**
	 * 
	 * @param email
	 * @param password - unhashed
	 * @return
	 */
	public boolean hasUser(String nickName, String password) {
		String passHash = LoginUtils.hash(password);
		return userDao.hasUser(nickName, passHash);
	}
	
	public boolean checkNick(String nick){
		return userDao.checkNick(nick);
	}
	
	public boolean checkEmail(String email){
		return userDao.checkNick(email);
	}
	
	
	public User getUserByNickName(String nickName){
		return userDao.getUserByNickName(nickName);
	}

	
	
	public List<User> getAllUsers() {
		return userDao.getAllUsers();
	}
	
	public User getUserById(long id) {
		return userDao.getUserById(id);
	}
	
	
	
}

src/sk/ibm/sa/jsf/FriendsBean.java
package sk.ibm.sa.jsf;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import sk.ibm.sa.Friends;
import sk.ibm.sa.User;
import sk.ibm.sa.dao.FriendsController;

@Named("friends")
@SessionScoped
public class FriendsBean implements Serializable {

	private FriendsController friendController;
	private List<User> friends;
	private List<User> noFriends;
	private Friends friend;
	
	
	
	
	
	public Friends getFriend() {
		return friend;
	}



	public void setFriend(Friends friend) {
		this.friend = friend;
	}



	public List<User> getNoFriends() {
		return noFriends;
	}



	public void setNoFriends(List<User> noFriends) {
		this.noFriends = noFriends;
	}



	public FriendsBean() {
		friendController = new FriendsController();
	}

	

	public List<User> getFriends() {
		return friends;
	}



	public void setFriends(List<User> friends) {
		this.friends = friends;
	}



	@PostConstruct
	public void init() {
		friends = new ArrayList<User>();
		noFriends = new ArrayList<User>();
		friend = new Friends();
	}
	
	public void loadFriendList(String id){
		friends = friendController.getFriendsList(Integer.parseInt(id));
	}
	
	public void loadNoFriendList(String id){
		noFriends = friendController.getNoFriendsList(Integer.parseInt(id));
	}
	
	public String friendsPage(){
		return "friends.xhtml?faces-redirect=true";
	}
	
	public void addFriends(String id1, String id2){
		friend.setUser_id1(Integer.parseInt(id1));
		friend.setUser_id2(Integer.parseInt(id2));
		friendController.addFriends(friend);
	}
}

src/sk/ibm/sa/jsf/LoginBean.java
package sk.ibm.sa.jsf;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.swing.plaf.synth.SynthSeparatorUI;

import sk.ibm.sa.Country;
import sk.ibm.sa.User;
import sk.ibm.sa.dao.UserController;
import sk.ibm.sa.utils.LoginUtils;

@Named("login")
@SessionScoped
public class LoginBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private UserController userController;

	/**
	 * password - unhashed
	 */
	private String password;
	private String nickName;
	private User user;
	
	public LoginBean() {
		userController = new UserController();
	}

	public Country[] getCountries() {
		return Country.values();
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public void loadUser() {
		user = userController.getUserByNickName(nickName);
	}
	
	public String login() {
		if (userController.hasUser(nickName, password)) {
						
			LoginUtils.setHttpSessionEmailAttribute(nickName);
			return "user.xhtml";
		} else {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Incorrect Nick or Password", "Incorrect Nick or Password"));
			return "index.xhtml?faces-redirect=true";
		}
	}

	
	public String logout() {
		LoginUtils.getHttpSession().invalidate();
		return "index.xhtml?faces-redirect=true";
	}

}

src/sk/ibm/sa/jsf/ProfileBean.java
package sk.ibm.sa.jsf;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import sk.ibm.sa.Post;
import sk.ibm.sa.User;
import sk.ibm.sa.dao.PostController;
import sk.ibm.sa.dao.UserController;

@Named("profile")
@RequestScoped
public class ProfileBean implements Serializable {

	private UserController userController;
	private PostController postController;
	private User user;
	private int id;
	private List<Post> posts;
	
	public ProfileBean() {
		userController = new UserController(); 
		postController = new PostController();
	}

	public User getUser() {
		return user;
	}
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	
	public List<Post> getPosts() {
		return posts;
	}

	public void setPosts(List<Post> posts) {
		this.posts = posts;
	}

	public void load() {
		user = userController.getUserById(id);
		posts = postController.getPostByUserId(id);
	}
	
	
}

WebContent/addFriend.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" template="userTemplate.xhtml">


	<ui:define name="content">

		<f:metadata>
			<f:event listener="#{friends.loadNoFriendList(login.user.id_user)}"
				type="preRenderView"></f:event>
		</f:metadata>

		<div class="jumbotron-white" style="padding-top: 80px">
			<div class="container">
				<h:dataTable value="#{friends.noFriends}" var="user"
					styleClass="table table-hover">
					<h:column>
						<f:facet name="header">Name</f:facet>
			#{user.name}
		</h:column>
					<h:column>
						<f:facet name="header">Surname</f:facet>
			#{user.surname}
		</h:column>
					<h:column>
						<f:facet name="header">Email</f:facet>
			#{user.email}
		</h:column>
					<h:column>
						<f:facet name="header"></f:facet>
						<h:link value="Profile" outcome="profile.xhtml" class="btn btn-info">
					<f:param name="id" value="#{user.id_user}" />
				</h:link>
					</h:column>
					<h:column>
					<h:form>
				<h:commandLink value="Add" action="#{friends.addFriends(login.user.id_user, user.id_user)}"  class="btn btn-success"/>
				</h:form>
					</h:column>
					
				</h:dataTable>
			</div>
		</div>
	</ui:define>

</ui:composition>

WebContent/commonContent.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron jumbotron-dirt">
		<div class="container">
			<h1>Welcome to Status!</h1>
			<blockquote>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
					vulputate rutrum eleifend. Nam faucibus, nibh eu pulvinar pharetra,
					nisi augue ornare turpis, at mattis lorem neque in quam. Vivamus mi
					metus, mattis a diam a, aliquam pharetra velit.</p>
				<footer>Tom Kingston, CEO </footer>
			</blockquote>
		</div>
	</div>

	<div class="jumbotron jumbotron-white">
		<div class="container">
			<div class="page-header">
				<h1>Sign in</h1>
			</div>
			<p class="lead">Morbi at tortor eu arcu dignissim lobortis.
				Phasellus sit amet libero aliquam, laoreet quam ut, posuere tellus.</p>

			<h:form class="form-horizontal" id="loginForm">

				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="nickLogin">Nick</h:outputLabel>
						<h:inputText id="nickLogin" class="form-control"
							value="#{login.nickName}" required="true"
							requiredMessage="Nick is required !" />
					</div>
				</div>

				<div class="form-group ">
					<div class="col-sm-3">
						<h:outputLabel for="password">Password</h:outputLabel>
						<h:inputSecret id="password" type="password" class="form-control"
							value="#{login.password}" required="true"
							requiredMessage="Password is required !" />
					</div>
				</div>

				<div class="form-group ">
					<div class="col-sm-3">
						<div class="bg-danger">
							<h:messages />
						</div>
						<h:commandButton id="submit" value="Sign in"
							action="#{login.login()}" class="btn btn-success">
						</h:commandButton>
					</div>
				</div>
			</h:form>

		</div>
	</div>

	<div class="jumbotron jumbotron-dirt">
		<div class="container">
			<div class="page-header">
				<h1>Register</h1>
			</div>
			<p class="lead">Morbi at tortor eu arcu dignissim lobortis.
				Phasellus sit amet libero aliquam, laoreet quam ut, posuere tellus.</p>
			<h:button value="Register" outcome="registerContent.html"
				class="btn btn-primary" />
		</div>
	</div>
</ui:composition>

WebContent/commonFooter.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets">


	<div class="container" style="margin-top: 4px; padding-top: 100px;">
		<p class="text-muted">IBM Summer Academy 2016 @Štefan Szűrös</p>
	</div>

</ui:composition>

WebContent/commonNavbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets">

	<nav id="navbar-blue" class="navbar navbar-default navbar-fixed-top navbar-min">
		<div class="container">
			<div class="navbar-header">
			</div>
		</div>
	</nav>

</ui:composition>

WebContent/friends.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" template="userTemplate.xhtml">


	<ui:define name="content">

		<f:metadata>
			<f:event listener="#{friends.loadFriendList(login.user.id_user)}"
				type="preRenderView"></f:event>
		</f:metadata>

		<div class="jumbotron-white" style="padding-top: 80px">
			<div class="container">
				<h:dataTable value="#{friends.friends}" var="user"
					styleClass="table table-hover">
					<h:column>
						<f:facet name="header">Name</f:facet>
			#{user.name}
		</h:column>
					<h:column>
						<f:facet name="header">Surname</f:facet>
			#{user.surname}
		</h:column>
					<h:column>
						<f:facet name="header">Email</f:facet>
			#{user.email}
		</h:column>
					<h:column>
						<f:facet name="header"></f:facet>
						<h:link value="Profile" outcome="profile.xhtml" class="btn btn-info">
					<f:param name="id" value="#{user.id_user}" />
				</h:link>
					</h:column>
				</h:dataTable>
			</div>
		</div>
	</ui:define>

</ui:composition>

WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>primestrap</title>
	</f:facet>

	<f:facet name="middle">
		<h:outputStylesheet name="bootstrap/css/bootstrap.css" />
		<h:outputStylesheet library="css" name="style.css"  />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" />
		<h:outputScript name="bootstrap/js/bootstrap.js" />
	</f:facet>

	<f:facet name="last">
	</f:facet>
</h:head>
<body>
	<div id="page">

		<div id="header">
			<ui:insert name="navbar">
				<ui:include src="commonNavbar.xhtml" />
			</ui:insert>
		</div>

		<div id="content">
			<ui:insert name="content">
				<ui:include src="commonContent.xhtml" />
			</ui:insert>
		</div>

		<div id="footer">
			<ui:insert name="footer">
				<ui:include src="commonFooter.xhtml" />
			</ui:insert>
		</div>

	</div>
	<!-- load js at bottom for faster loading-->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" />

</body>
</html>

WebContent/profile.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" template="userTemplate.xhtml">


	<ui:define name="content">

		<f:metadata>
			<f:viewParam name="id" value="#{profile.id}" />
			<f:event listener="#{profile.load()}" type="preRenderView"></f:event>
		</f:metadata>

		<div class="jumbotron-white" style="padding: 80px 0px">
			<div class="container">


				<h1>#{profile.user.name} #{profile.user.surname}</h1>
				<h2 style="padding-bottom:30px">#{profile.user.nickName}</h2>
				
				<div class=" col-md-9 col-lg-9 ">
					<table class="table table-user-information">
						<tbody>
							<tr>
								<td>Email:</td>
								<td>#{profile.user.email}</td>
							</tr>
							<tr>
								<td>City:</td>
								<td>#{profile.user.address.city}</td>
							</tr>
							<tr>
								<td>Postal code:</td>
								<td>#{profile.user.address.postalCode}</td>
							</tr>
							<tr>
								<td>Street:</td>
								<td>#{profile.user.address.street}</td>
							</tr>
							<tr>
								<td>Country:</td>
								<td>#{profile.user.address.country}</td>
							</tr>
						</tbody>
					</table>
				</div>
							
			</div>
			
			<div class="container" style="padding: 50px 0px">
			
			<ui:repeat var="post" value="#{profile.posts}">
					<div class="media" style="padding: 25px 0px">
						<a class="media-left" href="#"> <img class="media-object"
							data-src="..." alt="Profile picture" />
						</a>
						<div class="media-body">
							<h4 class="media-heading">#{post.user.name}
								#{post.user.surname}</h4>
							<div>#{post.date}</div>
							<hr />

							#{post.text}

						</div>
					</div>
				</ui:repeat>
			</div>
			
			
		</div>
	</ui:define>

</ui:composition>

WebContent/registerContent.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/index.xhtml">
	
	<ui:define name="content">
	<div class="jumbotron jumbotron-dirt">
		<div class="container">
			<div class="page-header">
				<h1>Register</h1>
			</div>
			<p class="lead">Nunc ut lorem at velit maximus tristique nec et
				mi. Duis pharetra finibus nunc, et sodales sem vulputate vitae.
				Aliquam mattis dignissim pretium. Donec eu egestas augue. In commodo
				tortor tellus, et semper eros euismod sit amet.
			</p>
			
			<h:form class="form-horizontal" id="registerForm">
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="name">Name</h:outputLabel>
						<h:inputText id="name" class="form-control"
							value="#{reg.user.name}" required="true"
							requiredMessage="Name is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="surname">Surname</h:outputLabel>
						<h:inputText id="surname" class="form-control"
							value="#{reg.user.surname}" required="true"
							requiredMessage="Surname is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="city">City</h:outputLabel>
						<h:inputText id="city" class="form-control"
							value="#{reg.user.address.city}" required="true"
							requiredMessage="City is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="street">Street</h:outputLabel>
						<h:inputText id="street" class="form-control"
							value="#{reg.user.address.street}" required="true"
							requiredMessage="Street is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="postalCode">Postal Code</h:outputLabel>
						<h:inputText id="postalCode" class="form-control"
							value="#{reg.user.address.postalCode}" required="true"
							requiredMessage="Postal Code is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="country">Country</h:outputLabel>
						<h:selectOneMenu id="country" value="#{reg.user.address.country}" class="form-control">
							<f:selectItems value="#{login.countries}"></f:selectItems>
						</h:selectOneMenu>
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="nick">Nick</h:outputLabel>
						<h:inputText id="nick" class="form-control"
							value="#{reg.user.nickName}" required="true"
							requiredMessage="Nick is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="emailRegister">Email</h:outputLabel>
						<h:inputText id="emailRegister" class="form-control"
							value="#{reg.user.email}" required="true"
							requiredMessage="Email is required !" />
					</div>
				</div>
				
				<div class="form-group">
					<div class="col-sm-3">
						<h:outputLabel for="passwordRegister">Password</h:outputLabel>
						<h:inputSecret id="passwordRegister" class="form-control"
							value="#{reg.user.password}" required="true"
							requiredMessage="Password is required !" />
					</div>
				</div>				
				
				<div class="form-group ">
					<div class="col-sm-3">
						<div class="bg-danger">
							<h:messages />
						</div>
						<h:commandButton id="submit" value="Register"
							action="#{reg.register()}" class="btn btn-primary" />
						<h:button value="Back" outcome="index.html" class="btn btn-default" />
					</div>
				</div>
			</h:form>
		</div>
	</div>
	</ui:define>
</ui:composition>

WebContent/user.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html" template="userTemplate.xhtml">
	
	<ui:define name="content">

	
	<f:metadata>
			<f:event listener="#{login.loadUser}" type="preRenderView"></f:event>
			<f:event listener="#{postBean.loadFriendPosts(login.user.id_user)}" type="preRenderView"></f:event>
		</f:metadata>
		
		<div class="jumbotron-white" style="padding-top: 20px;">
			<div class="container">
				<div class="page-header" style="text-align: center">
					<h1>Hello #{login.user.name} #{login.user.surname} !</h1>
				</div>

			<h:form style="padding-bottom: 80px">
				<div class="input-group col-sm-12" >
					<h:inputTextarea  id="text" class="form-control custom-control" rows="4"
						style="resize: none" value="#{postBean.post.text}" required="true">
					</h:inputTextarea >
				</div>
				<div class="input-group">
				<h:commandButton id="post" value="Post" class="btn btn-default" action="#{postBean.addPost(login.user.id_user)}">
				</h:commandButton>
				</div>
			</h:form>	
				
				
				<ui:repeat var="post" value="#{postBean.posts}">
					<div class="media" style="padding: 25px 0px">
					<a class="media-left" href="#"> <img class="media-object"
						data-src="..." alt="Profile picture" />
					</a>
					<div class="media-body">
						<h4 class="media-heading">#{post.user.name} #{post.user.surname}</h4>
						<div>#{post.date}</div>
						<hr/>
						
						#{post.text}
						
					</div>
					</div>
				</ui:repeat>
				</div>
				</div>
				
				
	</ui:define>

</ui:composition>

WebContent/userNavbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core">

   <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        
       			<h:link value="#{login.user.name} #{login.user.surname}" outcome="profile.xhtml" class="navbar-brand">
					<f:param name="id" value="#{login.user.id_user}" />
				</h:link>


			</div>
       
       
        <div id="navbar" class="navbar-collapse collapse">
          
           <h:form>
          <ul class="nav navbar-nav">
          <li><h:commandLink value="Home" action="user.xhtml?faces-rederict=true" /></li>
            <li><h:commandLink value="Friends" action="#{friends.friendsPage()}" /></li>
            <li><h:commandLink value="Add new friend" action="addFriend.xhtml?faces-rederict=true" /></li>
            </ul>
        </h:form>
          
          
          <h:form>
          <ul class="nav navbar-nav navbar-right">
         
           <li><h:commandLink value="Logout" action="#{login.logout()}" /></li>
          </ul>
            </h:form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

</ui:composition>

WebContent/userTemplate.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>primestrap</title>
	</f:facet>

	<f:facet name="middle">
		<h:outputStylesheet name="bootstrap/css/bootstrap.css" />
		<h:outputStylesheet library="css" name="style.css"  />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" />
		<h:outputScript name="bootstrap/js/bootstrap.js" />
	</f:facet>

	<f:facet name="last">
	</f:facet>
</h:head>
<body>

	<div id="page">

		<div id="header">
			<ui:insert name="navbar">
				<ui:include src="userNavbar.xhtml" />
			</ui:insert>
		</div>

		<div id="content">
			<ui:insert name="content">
			</ui:insert>
		</div>

		<div id="footer">
			<ui:insert name="footer">
				<ui:include src="commonFooter.xhtml" />
			</ui:insert>
		</div>

	</div>
	<!-- load js at bottom for faster loading-->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" />

</body>
</html>